"""Coupling matrix tests: mirror beta recovery, equivariance, spectral radius."""

from __future__ import annotations

import numpy as np
import pytest

from origami_lab.coupling import (
    MentalCoupling,
    apply_coupling,
    effective_rank,
    estimate_coupling,
    identity_coupling,
    mirror_coupling,
    mirror_coupling_matrix,
    spectral_radius,
)
from origami_lab.symmetry import klein_four_strip


def test_identity_coupling_diagonal() -> None:
    """Identity coupling should be the n x n identity matrix."""
    ic = identity_coupling(5)
    assert np.allclose(ic.matrix, np.eye(5), atol=1e-12)
    assert ic.beta == 0.0


def test_mirror_coupling_diagonal_is_one() -> None:
    """Diagonal entries of mirror coupling should be 1."""
    M = mirror_coupling_matrix(6, 0.4)
    assert np.allclose(np.diag(M), 1.0, atol=1e-12)


def test_mirror_coupling_off_diagonal() -> None:
    """Off-diagonal mirror entries should equal beta."""
    beta = 0.3
    n = 6
    M = mirror_coupling_matrix(n, beta)
    for i in range(n):
        j = n - 1 - i
        if j != i:
            assert np.isclose(M[i, j], beta, atol=1e-12), (
                f"M[{i},{j}] = {M[i,j]} expected {beta}"
            )


def test_mirror_coupling_odd_center() -> None:
    """Center hinge of odd-sized strip should have only diagonal contribution."""
    n = 5
    M = mirror_coupling_matrix(n, 0.5)
    center = n // 2
    # center row: only diagonal == 1, mirror index == self.
    row = M[center]
    assert np.isclose(row[center], 1.0, atol=1e-12)
    for j in range(n):
        if j != center:
            assert np.isclose(row[j], 0.0, atol=1e-12)


def test_mirror_coupling_beta_zero_is_identity() -> None:
    """Beta=0 mirror coupling should equal identity."""
    M = mirror_coupling_matrix(4, 0.0)
    assert np.allclose(M, np.eye(4), atol=1e-12)


def test_mirror_coupling_invalid_beta() -> None:
    """Beta outside [0,1] should raise ValueError."""
    with pytest.raises(ValueError):
        mirror_coupling_matrix(4, -0.1)
    with pytest.raises(ValueError):
        mirror_coupling_matrix(4, 1.1)


def test_mirror_coupling_eigenvalues() -> None:
    """Mirror coupling eigenvalues should be 1+beta, 1-beta (and 1 if odd n)."""
    beta = 0.4
    n = 4
    M = mirror_coupling_matrix(n, beta)
    eigvals = np.sort(np.linalg.eigvalsh(M))
    expected = np.sort([1 - beta] * (n // 2) + [1 + beta] * (n // 2))
    assert np.allclose(eigvals, expected, atol=1e-10)


def test_apply_coupling_identity() -> None:
    """apply_coupling with identity should return the intent unchanged."""
    ic = identity_coupling(4)
    intent = np.array([0.1, -0.2, 0.3, -0.4])
    result = apply_coupling(ic, intent)
    assert np.allclose(result, intent, atol=1e-12)


def test_apply_coupling_mirror() -> None:
    """apply_coupling with mirror coupling: output = intent + beta * reversed(intent)."""
    beta = 0.5
    n = 4
    mc = mirror_coupling(n, beta)
    intent = np.array([0.1, 0.2, 0.3, 0.4])
    result = apply_coupling(mc, intent)
    expected = intent + beta * intent[::-1]
    assert np.allclose(result, expected, atol=1e-12)


def test_apply_coupling_angle_max_clamps() -> None:
    """apply_coupling should clamp output when angle_max is provided."""
    mc = mirror_coupling(2, 0.9)
    intent = np.array([np.pi, np.pi])
    result = apply_coupling(mc, intent, angle_max=np.pi)
    assert np.all(np.abs(result) <= np.pi + 1e-12)


def test_estimate_coupling_identity_data() -> None:
    """When responses == intents, estimated C should be close to identity."""
    rng = np.random.default_rng(42)
    n = 4
    K = 100
    X = rng.standard_normal((K, n))
    C = estimate_coupling(X, X, n_hinges=n)
    assert np.allclose(C, np.eye(n), atol=1e-6)


def test_estimate_coupling_mirror_recovery() -> None:
    """Given data generated by mirror coupling, recovery should reproduce beta."""
    rng = np.random.default_rng(99)
    beta = 0.35
    n = 6
    K = 500
    M = mirror_coupling_matrix(n, beta)
    X = rng.standard_normal((K, n))
    Y = (M @ X.T).T
    C = estimate_coupling(X, Y, n_hinges=n)
    assert np.allclose(C, M, atol=1e-6), f"Max diff = {np.abs(C - M).max()}"


def test_estimate_coupling_v4_projection() -> None:
    """V_4 projected estimate should be equivariant."""
    rng = np.random.default_rng(7)
    n = 4
    K = 100
    X = rng.standard_normal((K, n))
    Y = X + 0.3 * rng.standard_normal((K, n))
    C = estimate_coupling(X, Y, n_hinges=n, use_v4=True)
    G = klein_four_strip(n)
    mc = MentalCoupling(matrix=C, n_hinges=n, source="empirical")
    from origami_lab.coupling import coupling_equivariance_residual
    residual = coupling_equivariance_residual(mc, G)
    assert residual < 1e-9, f"Equivariance residual too large: {residual}"


def test_spectral_radius_identity() -> None:
    """Spectral radius of identity should be 1."""
    rho = spectral_radius(np.eye(5))
    assert np.isclose(rho, 1.0, atol=1e-9)


def test_spectral_radius_mirror() -> None:
    """Spectral radius of mirror(n, beta) should be 1 + beta."""
    beta = 0.6
    n = 4
    M = mirror_coupling_matrix(n, beta)
    rho = spectral_radius(M)
    assert np.isclose(rho, 1.0 + beta, atol=1e-6)


def test_effective_rank_identity() -> None:
    """Effective rank of nxn identity is n."""
    n = 5
    assert effective_rank(np.eye(n)) == n


def test_effective_rank_rank_one() -> None:
    """Effective rank of rank-1 matrix is 1."""
    v = np.array([1.0, 2.0, 3.0])
    M = np.outer(v, v)
    assert effective_rank(M) == 1


def test_coupling_equivariance_residual_analytic() -> None:
    """Analytically constructed mirror coupling should have zero equivariance residual."""
    n = 6
    mc = mirror_coupling(n, 0.4)
    G = klein_four_strip(n)
    from origami_lab.coupling import coupling_equivariance_residual
    residual = coupling_equivariance_residual(mc, G)
    assert residual < 1e-9, f"Residual = {residual}"
