"""Parity test with TypeScript @kinemind/core-math.

Loads a golden JSON file generated by the TypeScript forwardKinematics
implementation and verifies that the Python implementation reproduces
positions and quaternions at atol=1e-9.

Also verifies SAT collision parity: i/j indices must agree exactly,
penetration depth within atol=1e-12 of the TS implementation.

Golden file: tests/data/golden_strip_8.json
Generated by: TypeScript @kinemind/core-math forwardKinematics
  config: 8 cells, uniform length=1, angleMax=pi
  state: thetas=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from origami_lab.collision import detect_self_intersection_sat, quad_quad_overlap
from origami_lab.kinematics import forward_kinematics, forward_kinematics_full
from origami_lab.strip import StripConfig, StripState

GOLDEN_PATH = Path(__file__).parent / "data" / "golden_strip_8.json"
ATOL = 1e-9


@pytest.fixture(scope="module")
def golden() -> dict:
    """Load the golden JSON file."""
    if not GOLDEN_PATH.exists():
        pytest.skip(f"Golden file not found: {GOLDEN_PATH}")
    with open(GOLDEN_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _build_config(cfg: dict) -> StripConfig:
    """Reconstruct StripConfig from golden dict."""
    return StripConfig(
        n_cells=int(cfg["nCells"]),
        cell_lengths=tuple(float(x) for x in cfg["cellLengths"]),
        angle_max=float(cfg.get("angleMax", math.pi)),
    )


def _build_state(st: dict) -> StripState:
    """Reconstruct StripState from golden dict."""
    return StripState(thetas=tuple(float(x) for x in st["thetas"]))


def test_golden_positions_match(golden: dict) -> None:
    """Python positions must match TypeScript positions at atol=1e-9."""
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    positions_py, _ = forward_kinematics(config, state)
    positions_ts = np.array(golden["positions"], dtype=np.float64)

    assert positions_py.shape == positions_ts.shape, (
        f"Shape mismatch: {positions_py.shape} vs {positions_ts.shape}"
    )
    if not np.allclose(positions_py, positions_ts, atol=ATOL):
        diff = np.abs(positions_py - positions_ts)
        max_idx = np.unravel_index(np.argmax(diff), diff.shape)
        pytest.fail(
            f"Positions mismatch: max diff = {diff.max():.2e} at {max_idx}. "
            f"Python: {positions_py[max_idx[0]]}, TS: {positions_ts[max_idx[0]]}"
        )


def test_golden_quats_match(golden: dict) -> None:
    """Python quaternions must match TypeScript quaternions at atol=1e-9 (up to sign)."""
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    _, quats_py = forward_kinematics(config, state)
    quats_ts = np.array(golden["quats"], dtype=np.float64)

    assert quats_py.shape == quats_ts.shape, (
        f"Shape mismatch: {quats_py.shape} vs {quats_ts.shape}"
    )
    for i in range(quats_py.shape[0]):
        q_py = quats_py[i]
        q_ts = quats_ts[i]
        if not (
            np.allclose(q_py, q_ts, atol=ATOL)
            or np.allclose(q_py, -q_ts, atol=ATOL)
        ):
            pytest.fail(
                f"Quaternion mismatch at cell {i}: "
                f"Python={q_py}, TS={q_ts}, diff={np.abs(q_py - q_ts)}"
            )


def test_golden_config_round_trip(golden: dict) -> None:
    """Config reconstructed from golden dict should have correct dimensions."""
    config = _build_config(golden["config"])
    assert config.n_cells == golden["config"]["nCells"]
    assert config.n_hinges == golden["config"]["nCells"] - 1
    assert len(config.cell_lengths) == config.n_cells


def test_golden_state_dimensions(golden: dict) -> None:
    """State should have n_cells - 1 hinge angles."""
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    assert len(state.thetas) == config.n_hinges


def test_golden_cell_0_at_origin(golden: dict) -> None:
    """Cell 0 must always be at world origin."""
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    positions, _ = forward_kinematics(config, state)
    assert np.allclose(positions[0], np.zeros(3), atol=1e-12)


def test_parity_all_cells_y_zero(golden: dict) -> None:
    """For a planar strip (no out-of-plane rotations), y-coordinates should be zero.

    All hinges rotate about +Y, so the strip stays in the XZ plane:
    all y-coordinates must remain 0.
    """
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    positions, _ = forward_kinematics(config, state)
    assert np.allclose(positions[:, 1], 0.0, atol=1e-12), (
        f"Y-coords not zero: {positions[:, 1]}"
    )


def test_parity_quats_unit_norm(golden: dict) -> None:
    """All quaternions must have unit norm."""
    config = _build_config(golden["config"])
    state = _build_state(golden["state"])
    _, quats = forward_kinematics(config, state)
    norms = np.linalg.norm(quats, axis=1)
    assert np.allclose(norms, 1.0, atol=1e-12), (
        f"Quaternion norms deviate from 1: {norms}"
    )


# ---------------------------------------------------------------------------
# SAT collision parity (TS ↔ Python, atol=1e-12)
#
# Golden values computed from TypeScript quadQuadOverlap / detectSelfIntersectionSat.
# Cases were designed to exercise: non-overlap, coplanar overlap, 3D near-coplanar,
# accordion fold, and large penetration.
# ---------------------------------------------------------------------------

# Five golden collision cases:
#   (qa, qb, expected_result)
# expected_result = None means no overlap; otherwise (i, j, penetration) where
# i/j are dummy 0,0 for direct quad tests, and penetration atol=1e-12.
_COLLISION_CASES: list[dict] = [
    {
        "desc": "non-overlapping separated quads → None",
        "qa": [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
        "qb": [[2, 0, 0], [3, 0, 0], [3, 1, 0], [2, 1, 0]],
        "overlap": False,
        "penetration": None,
    },
    {
        "desc": "coplanar XY overlap by 0.5 in X → penetration = 0.5",
        "qa": [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
        "qb": [[0.5, 0, 0], [1.5, 0, 0], [1.5, 1, 0], [0.5, 1, 0]],
        "overlap": True,
        "penetration": 0.5,
    },
    {
        "desc": "coplanar XZ overlap by 0.5 → penetration = 0.5",
        "qa": [[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1]],
        "qb": [[0.5, 0, 0], [1.5, 0, 0], [1.5, 0, 1], [0.5, 0, 1]],
        "overlap": True,
        "penetration": 0.5,
    },
    {
        "desc": "quads at z=0 and z=2 → separated along face normal",
        "qa": [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
        "qb": [[0, 0, 2], [1, 0, 2], [1, 1, 2], [0, 1, 2]],
        "overlap": False,
        "penetration": None,
    },
    {
        "desc": "fully overlapping congruent quads → penetration = 1",
        "qa": [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
        "qb": [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
        "overlap": True,
        "penetration": 1.0,
    },
]


@pytest.mark.parametrize("case", _COLLISION_CASES, ids=[c["desc"] for c in _COLLISION_CASES])
def test_collision_parity_quad_quad(case: dict) -> None:
    """Python quad_quad_overlap must match TS golden values at atol=1e-12."""
    qa = np.array(case["qa"], dtype=np.float64)
    qb = np.array(case["qb"], dtype=np.float64)
    result = quad_quad_overlap(qa, qb)
    if not case["overlap"]:
        assert result is None, f"Expected None for case: {case['desc']}"
    else:
        assert result is not None, f"Expected overlap for case: {case['desc']}"
        _, penetration = result
        expected_pen = case["penetration"]
        assert abs(penetration - expected_pen) < 1e-12, (
            f"Penetration mismatch: got {penetration}, expected {expected_pen} "
            f"(case: {case['desc']})"
        )


def test_collision_parity_accordion_fold_ij() -> None:
    """Python and TS must agree on (i,j) pair indices for accordion fold at atol=0."""
    from origami_lab.strip import make_uniform_strip

    config = make_uniform_strip(4, cell_length=1.0)
    state = StripState(thetas=(math.pi, math.pi, 0.0))
    result = forward_kinematics_full(config, state)
    hits = detect_self_intersection_sat(config, result)
    # TS golden: at least (0, 2) pair present with j > i+1.
    ij_pairs = [(h.i, h.j) for h in hits]
    assert (0, 2) in ij_pairs, f"Expected (0,2) in {ij_pairs}"
    # All pairs must have j > i+1 (TS invariant).
    for h in hits:
        assert h.j > h.i + 1
